### ISSUE TITLE
AMF failed with error: AMF_ENCODER_NOT_PRESENT

### ISSUE THREAD

**Issue by Thanakil** [jackun/TestAMFVFW#4]
I followed the steps given: got the runtimes, installed As Administrator.
I tried using it with Dxtory but when I start recording, I get this error: AMF failed with error: AMF_ENCODER_NOT_PRESENT.
I tried reinstalling and trying again, but no dice. I'm not sure what to do.

**Comment by jackun** [comment]
What hardware etc.? You can try cleaning with [DDU](http://www.wagnardmobile.com/forums/viewforum.php?f=5) and then reinstall drivers, but sometimes it gives the ..._NOT_PRESET error with unsupported resolution, IIRC.

**Comment by Thanakil** [comment]
Edit:
I'm sorry, I think I found the culprit. It was SetPoint.
Dxtory would detect SetPoint over my games and try to record it for some reason. This caused the issue, most likely because of the resolution issue you mentioned.
With it closed, recording works. Sorry about that.
